files:
  - source: app/src/main/res/values/strings.xml
    translation: >-
      app/src/main/res/values-%two_letters_code%-%three_letters_code%/%original_file_name%
    translate_attributes: '0'
    content_segmentation: '0'
