/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.chilkatsoft;

public class CkBaseProgress {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CkBaseProgress(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CkBaseProgress obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        chilkatJNI.delete_CkBaseProgress(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    chilkatJNI.CkBaseProgress_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    chilkatJNI.CkBaseProgress_change_ownership(this, swigCPtr, true);
  }

  public CkBaseProgress() {
    this(chilkatJNI.new_CkBaseProgress(), true);
    chilkatJNI.CkBaseProgress_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public boolean AbortCheck() {
    return (getClass() == CkBaseProgress.class) ? chilkatJNI.CkBaseProgress_AbortCheck(swigCPtr, this) : chilkatJNI.CkBaseProgress_AbortCheckSwigExplicitCkBaseProgress(swigCPtr, this);
  }

  public boolean PercentDone(int pctDone) {
    return (getClass() == CkBaseProgress.class) ? chilkatJNI.CkBaseProgress_PercentDone(swigCPtr, this, pctDone) : chilkatJNI.CkBaseProgress_PercentDoneSwigExplicitCkBaseProgress(swigCPtr, this, pctDone);
  }

  public void ProgressInfo(String name, String value) {
    if (getClass() == CkBaseProgress.class) chilkatJNI.CkBaseProgress_ProgressInfo(swigCPtr, this, name, value); else chilkatJNI.CkBaseProgress_ProgressInfoSwigExplicitCkBaseProgress(swigCPtr, this, name, value);
  }

  public void TaskCompleted(CkTask task) {
    if (getClass() == CkBaseProgress.class) chilkatJNI.CkBaseProgress_TaskCompleted(swigCPtr, this, CkTask.getCPtr(task), task); else chilkatJNI.CkBaseProgress_TaskCompletedSwigExplicitCkBaseProgress(swigCPtr, this, CkTask.getCPtr(task), task);
  }

  public void TextData(String data) {
    if (getClass() == CkBaseProgress.class) chilkatJNI.CkBaseProgress_TextData(swigCPtr, this, data); else chilkatJNI.CkBaseProgress_TextDataSwigExplicitCkBaseProgress(swigCPtr, this, data);
  }

}
