/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.chilkatsoft;

public class CkMailMan {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CkMailMan(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CkMailMan obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        chilkatJNI.delete_CkMailMan(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CkMailMan() {
    this(chilkatJNI.new_CkMailMan(), true);
  }

  public void LastErrorXml(CkString str) {
    chilkatJNI.CkMailMan_LastErrorXml(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public void LastErrorHtml(CkString str) {
    chilkatJNI.CkMailMan_LastErrorHtml(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public void LastErrorText(CkString str) {
    chilkatJNI.CkMailMan_LastErrorText(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public void put_EventCallbackObject(CkMailManProgress progress) {
    chilkatJNI.CkMailMan_put_EventCallbackObject(swigCPtr, this, CkMailManProgress.getCPtr(progress), progress);
  }

  public void get_LastErrorHtml(CkString str) {
    chilkatJNI.CkMailMan_get_LastErrorHtml(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String lastErrorHtml() {
    return chilkatJNI.CkMailMan_lastErrorHtml(swigCPtr, this);
  }

  public void get_LastErrorText(CkString str) {
    chilkatJNI.CkMailMan_get_LastErrorText(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String lastErrorText() {
    return chilkatJNI.CkMailMan_lastErrorText(swigCPtr, this);
  }

  public void get_LastErrorXml(CkString str) {
    chilkatJNI.CkMailMan_get_LastErrorXml(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String lastErrorXml() {
    return chilkatJNI.CkMailMan_lastErrorXml(swigCPtr, this);
  }

  public void get_Version(CkString str) {
    chilkatJNI.CkMailMan_get_Version(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String version() {
    return chilkatJNI.CkMailMan_version(swigCPtr, this);
  }

  public void get_DebugLogFilePath(CkString str) {
    chilkatJNI.CkMailMan_get_DebugLogFilePath(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String debugLogFilePath() {
    return chilkatJNI.CkMailMan_debugLogFilePath(swigCPtr, this);
  }

  public void put_DebugLogFilePath(String newVal) {
    chilkatJNI.CkMailMan_put_DebugLogFilePath(swigCPtr, this, newVal);
  }

  public boolean get_VerboseLogging() {
    return chilkatJNI.CkMailMan_get_VerboseLogging(swigCPtr, this);
  }

  public void put_VerboseLogging(boolean newVal) {
    chilkatJNI.CkMailMan_put_VerboseLogging(swigCPtr, this, newVal);
  }

  public boolean get_LastMethodSuccess() {
    return chilkatJNI.CkMailMan_get_LastMethodSuccess(swigCPtr, this);
  }

  public void put_LastMethodSuccess(boolean newVal) {
    chilkatJNI.CkMailMan_put_LastMethodSuccess(swigCPtr, this, newVal);
  }

  public boolean SaveLastError(String path) {
    return chilkatJNI.CkMailMan_SaveLastError(swigCPtr, this, path);
  }

  public boolean get_AbortCurrent() {
    return chilkatJNI.CkMailMan_get_AbortCurrent(swigCPtr, this);
  }

  public void put_AbortCurrent(boolean newVal) {
    chilkatJNI.CkMailMan_put_AbortCurrent(swigCPtr, this, newVal);
  }

  public boolean get_AllOrNone() {
    return chilkatJNI.CkMailMan_get_AllOrNone(swigCPtr, this);
  }

  public void put_AllOrNone(boolean newVal) {
    chilkatJNI.CkMailMan_put_AllOrNone(swigCPtr, this, newVal);
  }

  public boolean get_AutoFix() {
    return chilkatJNI.CkMailMan_get_AutoFix(swigCPtr, this);
  }

  public void put_AutoFix(boolean newVal) {
    chilkatJNI.CkMailMan_put_AutoFix(swigCPtr, this, newVal);
  }

  public boolean get_AutoGenMessageId() {
    return chilkatJNI.CkMailMan_get_AutoGenMessageId(swigCPtr, this);
  }

  public void put_AutoGenMessageId(boolean newVal) {
    chilkatJNI.CkMailMan_put_AutoGenMessageId(swigCPtr, this, newVal);
  }

  public boolean get_AutoSmtpRset() {
    return chilkatJNI.CkMailMan_get_AutoSmtpRset(swigCPtr, this);
  }

  public void put_AutoSmtpRset(boolean newVal) {
    chilkatJNI.CkMailMan_put_AutoSmtpRset(swigCPtr, this, newVal);
  }

  public boolean get_AutoUnwrapSecurity() {
    return chilkatJNI.CkMailMan_get_AutoUnwrapSecurity(swigCPtr, this);
  }

  public void put_AutoUnwrapSecurity(boolean newVal) {
    chilkatJNI.CkMailMan_put_AutoUnwrapSecurity(swigCPtr, this, newVal);
  }

  public void get_ClientIpAddress(CkString str) {
    chilkatJNI.CkMailMan_get_ClientIpAddress(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String clientIpAddress() {
    return chilkatJNI.CkMailMan_clientIpAddress(swigCPtr, this);
  }

  public void put_ClientIpAddress(String newVal) {
    chilkatJNI.CkMailMan_put_ClientIpAddress(swigCPtr, this, newVal);
  }

  public int get_ConnectFailReason() {
    return chilkatJNI.CkMailMan_get_ConnectFailReason(swigCPtr, this);
  }

  public int get_ConnectTimeout() {
    return chilkatJNI.CkMailMan_get_ConnectTimeout(swigCPtr, this);
  }

  public void put_ConnectTimeout(int newVal) {
    chilkatJNI.CkMailMan_put_ConnectTimeout(swigCPtr, this, newVal);
  }

  public void get_DsnEnvid(CkString str) {
    chilkatJNI.CkMailMan_get_DsnEnvid(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String dsnEnvid() {
    return chilkatJNI.CkMailMan_dsnEnvid(swigCPtr, this);
  }

  public void put_DsnEnvid(String newVal) {
    chilkatJNI.CkMailMan_put_DsnEnvid(swigCPtr, this, newVal);
  }

  public void get_DsnNotify(CkString str) {
    chilkatJNI.CkMailMan_get_DsnNotify(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String dsnNotify() {
    return chilkatJNI.CkMailMan_dsnNotify(swigCPtr, this);
  }

  public void put_DsnNotify(String newVal) {
    chilkatJNI.CkMailMan_put_DsnNotify(swigCPtr, this, newVal);
  }

  public void get_DsnRet(CkString str) {
    chilkatJNI.CkMailMan_get_DsnRet(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String dsnRet() {
    return chilkatJNI.CkMailMan_dsnRet(swigCPtr, this);
  }

  public void put_DsnRet(String newVal) {
    chilkatJNI.CkMailMan_put_DsnRet(swigCPtr, this, newVal);
  }

  public boolean get_EmbedCertChain() {
    return chilkatJNI.CkMailMan_get_EmbedCertChain(swigCPtr, this);
  }

  public void put_EmbedCertChain(boolean newVal) {
    chilkatJNI.CkMailMan_put_EmbedCertChain(swigCPtr, this, newVal);
  }

  public void get_Filter(CkString str) {
    chilkatJNI.CkMailMan_get_Filter(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String filter() {
    return chilkatJNI.CkMailMan_filter(swigCPtr, this);
  }

  public void put_Filter(String newVal) {
    chilkatJNI.CkMailMan_put_Filter(swigCPtr, this, newVal);
  }

  public int get_HeartbeatMs() {
    return chilkatJNI.CkMailMan_get_HeartbeatMs(swigCPtr, this);
  }

  public void put_HeartbeatMs(int newVal) {
    chilkatJNI.CkMailMan_put_HeartbeatMs(swigCPtr, this, newVal);
  }

  public void get_HeloHostname(CkString str) {
    chilkatJNI.CkMailMan_get_HeloHostname(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String heloHostname() {
    return chilkatJNI.CkMailMan_heloHostname(swigCPtr, this);
  }

  public void put_HeloHostname(String newVal) {
    chilkatJNI.CkMailMan_put_HeloHostname(swigCPtr, this, newVal);
  }

  public void get_HttpProxyAuthMethod(CkString str) {
    chilkatJNI.CkMailMan_get_HttpProxyAuthMethod(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String httpProxyAuthMethod() {
    return chilkatJNI.CkMailMan_httpProxyAuthMethod(swigCPtr, this);
  }

  public void put_HttpProxyAuthMethod(String newVal) {
    chilkatJNI.CkMailMan_put_HttpProxyAuthMethod(swigCPtr, this, newVal);
  }

  public void get_HttpProxyDomain(CkString str) {
    chilkatJNI.CkMailMan_get_HttpProxyDomain(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String httpProxyDomain() {
    return chilkatJNI.CkMailMan_httpProxyDomain(swigCPtr, this);
  }

  public void put_HttpProxyDomain(String newVal) {
    chilkatJNI.CkMailMan_put_HttpProxyDomain(swigCPtr, this, newVal);
  }

  public void get_HttpProxyHostname(CkString str) {
    chilkatJNI.CkMailMan_get_HttpProxyHostname(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String httpProxyHostname() {
    return chilkatJNI.CkMailMan_httpProxyHostname(swigCPtr, this);
  }

  public void put_HttpProxyHostname(String newVal) {
    chilkatJNI.CkMailMan_put_HttpProxyHostname(swigCPtr, this, newVal);
  }

  public void get_HttpProxyPassword(CkString str) {
    chilkatJNI.CkMailMan_get_HttpProxyPassword(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String httpProxyPassword() {
    return chilkatJNI.CkMailMan_httpProxyPassword(swigCPtr, this);
  }

  public void put_HttpProxyPassword(String newVal) {
    chilkatJNI.CkMailMan_put_HttpProxyPassword(swigCPtr, this, newVal);
  }

  public int get_HttpProxyPort() {
    return chilkatJNI.CkMailMan_get_HttpProxyPort(swigCPtr, this);
  }

  public void put_HttpProxyPort(int newVal) {
    chilkatJNI.CkMailMan_put_HttpProxyPort(swigCPtr, this, newVal);
  }

  public void get_HttpProxyUsername(CkString str) {
    chilkatJNI.CkMailMan_get_HttpProxyUsername(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String httpProxyUsername() {
    return chilkatJNI.CkMailMan_httpProxyUsername(swigCPtr, this);
  }

  public void put_HttpProxyUsername(String newVal) {
    chilkatJNI.CkMailMan_put_HttpProxyUsername(swigCPtr, this, newVal);
  }

  public boolean get_ImmediateDelete() {
    return chilkatJNI.CkMailMan_get_ImmediateDelete(swigCPtr, this);
  }

  public void put_ImmediateDelete(boolean newVal) {
    chilkatJNI.CkMailMan_put_ImmediateDelete(swigCPtr, this, newVal);
  }

  public boolean get_IncludeRootCert() {
    return chilkatJNI.CkMailMan_get_IncludeRootCert(swigCPtr, this);
  }

  public void put_IncludeRootCert(boolean newVal) {
    chilkatJNI.CkMailMan_put_IncludeRootCert(swigCPtr, this, newVal);
  }

  public boolean get_IsPop3Connected() {
    return chilkatJNI.CkMailMan_get_IsPop3Connected(swigCPtr, this);
  }

  public boolean get_IsSmtpConnected() {
    return chilkatJNI.CkMailMan_get_IsSmtpConnected(swigCPtr, this);
  }

  public void get_LastSendQFilename(CkString str) {
    chilkatJNI.CkMailMan_get_LastSendQFilename(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String lastSendQFilename() {
    return chilkatJNI.CkMailMan_lastSendQFilename(swigCPtr, this);
  }

  public int get_LastSmtpStatus() {
    return chilkatJNI.CkMailMan_get_LastSmtpStatus(swigCPtr, this);
  }

  public void get_LogMailReceivedFilename(CkString str) {
    chilkatJNI.CkMailMan_get_LogMailReceivedFilename(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String logMailReceivedFilename() {
    return chilkatJNI.CkMailMan_logMailReceivedFilename(swigCPtr, this);
  }

  public void put_LogMailReceivedFilename(String newVal) {
    chilkatJNI.CkMailMan_put_LogMailReceivedFilename(swigCPtr, this, newVal);
  }

  public void get_LogMailSentFilename(CkString str) {
    chilkatJNI.CkMailMan_get_LogMailSentFilename(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String logMailSentFilename() {
    return chilkatJNI.CkMailMan_logMailSentFilename(swigCPtr, this);
  }

  public void put_LogMailSentFilename(String newVal) {
    chilkatJNI.CkMailMan_put_LogMailSentFilename(swigCPtr, this, newVal);
  }

  public void get_MailHost(CkString str) {
    chilkatJNI.CkMailMan_get_MailHost(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String mailHost() {
    return chilkatJNI.CkMailMan_mailHost(swigCPtr, this);
  }

  public void put_MailHost(String newVal) {
    chilkatJNI.CkMailMan_put_MailHost(swigCPtr, this, newVal);
  }

  public int get_MailPort() {
    return chilkatJNI.CkMailMan_get_MailPort(swigCPtr, this);
  }

  public void put_MailPort(int newVal) {
    chilkatJNI.CkMailMan_put_MailPort(swigCPtr, this, newVal);
  }

  public int get_MaxCount() {
    return chilkatJNI.CkMailMan_get_MaxCount(swigCPtr, this);
  }

  public void put_MaxCount(int newVal) {
    chilkatJNI.CkMailMan_put_MaxCount(swigCPtr, this, newVal);
  }

  public void get_OAuth2AccessToken(CkString str) {
    chilkatJNI.CkMailMan_get_OAuth2AccessToken(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String oAuth2AccessToken() {
    return chilkatJNI.CkMailMan_oAuth2AccessToken(swigCPtr, this);
  }

  public void put_OAuth2AccessToken(String newVal) {
    chilkatJNI.CkMailMan_put_OAuth2AccessToken(swigCPtr, this, newVal);
  }

  public boolean get_OpaqueSigning() {
    return chilkatJNI.CkMailMan_get_OpaqueSigning(swigCPtr, this);
  }

  public void put_OpaqueSigning(boolean newVal) {
    chilkatJNI.CkMailMan_put_OpaqueSigning(swigCPtr, this, newVal);
  }

  public void get_P7mEncryptAttachFilename(CkString str) {
    chilkatJNI.CkMailMan_get_P7mEncryptAttachFilename(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String p7mEncryptAttachFilename() {
    return chilkatJNI.CkMailMan_p7mEncryptAttachFilename(swigCPtr, this);
  }

  public void put_P7mEncryptAttachFilename(String newVal) {
    chilkatJNI.CkMailMan_put_P7mEncryptAttachFilename(swigCPtr, this, newVal);
  }

  public void get_P7mSigAttachFilename(CkString str) {
    chilkatJNI.CkMailMan_get_P7mSigAttachFilename(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String p7mSigAttachFilename() {
    return chilkatJNI.CkMailMan_p7mSigAttachFilename(swigCPtr, this);
  }

  public void put_P7mSigAttachFilename(String newVal) {
    chilkatJNI.CkMailMan_put_P7mSigAttachFilename(swigCPtr, this, newVal);
  }

  public void get_P7sSigAttachFilename(CkString str) {
    chilkatJNI.CkMailMan_get_P7sSigAttachFilename(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String p7sSigAttachFilename() {
    return chilkatJNI.CkMailMan_p7sSigAttachFilename(swigCPtr, this);
  }

  public void put_P7sSigAttachFilename(String newVal) {
    chilkatJNI.CkMailMan_put_P7sSigAttachFilename(swigCPtr, this, newVal);
  }

  public int get_PercentDoneScale() {
    return chilkatJNI.CkMailMan_get_PercentDoneScale(swigCPtr, this);
  }

  public void put_PercentDoneScale(int newVal) {
    chilkatJNI.CkMailMan_put_PercentDoneScale(swigCPtr, this, newVal);
  }

  public boolean get_Pop3SPA() {
    return chilkatJNI.CkMailMan_get_Pop3SPA(swigCPtr, this);
  }

  public void put_Pop3SPA(boolean newVal) {
    chilkatJNI.CkMailMan_put_Pop3SPA(swigCPtr, this, newVal);
  }

  public int get_Pop3SessionId() {
    return chilkatJNI.CkMailMan_get_Pop3SessionId(swigCPtr, this);
  }

  public void get_Pop3SessionLog(CkString str) {
    chilkatJNI.CkMailMan_get_Pop3SessionLog(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String pop3SessionLog() {
    return chilkatJNI.CkMailMan_pop3SessionLog(swigCPtr, this);
  }

  public boolean get_Pop3SslServerCertVerified() {
    return chilkatJNI.CkMailMan_get_Pop3SslServerCertVerified(swigCPtr, this);
  }

  public boolean get_Pop3Stls() {
    return chilkatJNI.CkMailMan_get_Pop3Stls(swigCPtr, this);
  }

  public void put_Pop3Stls(boolean newVal) {
    chilkatJNI.CkMailMan_put_Pop3Stls(swigCPtr, this, newVal);
  }

  public void get_PopPassword(CkString str) {
    chilkatJNI.CkMailMan_get_PopPassword(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String popPassword() {
    return chilkatJNI.CkMailMan_popPassword(swigCPtr, this);
  }

  public void put_PopPassword(String newVal) {
    chilkatJNI.CkMailMan_put_PopPassword(swigCPtr, this, newVal);
  }

  public void get_PopPasswordBase64(CkString str) {
    chilkatJNI.CkMailMan_get_PopPasswordBase64(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String popPasswordBase64() {
    return chilkatJNI.CkMailMan_popPasswordBase64(swigCPtr, this);
  }

  public void put_PopPasswordBase64(String newVal) {
    chilkatJNI.CkMailMan_put_PopPasswordBase64(swigCPtr, this, newVal);
  }

  public boolean get_PopSsl() {
    return chilkatJNI.CkMailMan_get_PopSsl(swigCPtr, this);
  }

  public void put_PopSsl(boolean newVal) {
    chilkatJNI.CkMailMan_put_PopSsl(swigCPtr, this, newVal);
  }

  public void get_PopUsername(CkString str) {
    chilkatJNI.CkMailMan_get_PopUsername(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String popUsername() {
    return chilkatJNI.CkMailMan_popUsername(swigCPtr, this);
  }

  public void put_PopUsername(String newVal) {
    chilkatJNI.CkMailMan_put_PopUsername(swigCPtr, this, newVal);
  }

  public boolean get_PreferIpv6() {
    return chilkatJNI.CkMailMan_get_PreferIpv6(swigCPtr, this);
  }

  public void put_PreferIpv6(boolean newVal) {
    chilkatJNI.CkMailMan_put_PreferIpv6(swigCPtr, this, newVal);
  }

  public int get_ReadTimeout() {
    return chilkatJNI.CkMailMan_get_ReadTimeout(swigCPtr, this);
  }

  public void put_ReadTimeout(int newVal) {
    chilkatJNI.CkMailMan_put_ReadTimeout(swigCPtr, this, newVal);
  }

  public boolean get_RequireSslCertVerify() {
    return chilkatJNI.CkMailMan_get_RequireSslCertVerify(swigCPtr, this);
  }

  public void put_RequireSslCertVerify(boolean newVal) {
    chilkatJNI.CkMailMan_put_RequireSslCertVerify(swigCPtr, this, newVal);
  }

  public boolean get_ResetDateOnLoad() {
    return chilkatJNI.CkMailMan_get_ResetDateOnLoad(swigCPtr, this);
  }

  public void put_ResetDateOnLoad(boolean newVal) {
    chilkatJNI.CkMailMan_put_ResetDateOnLoad(swigCPtr, this, newVal);
  }

  public int get_SendBufferSize() {
    return chilkatJNI.CkMailMan_get_SendBufferSize(swigCPtr, this);
  }

  public void put_SendBufferSize(int newVal) {
    chilkatJNI.CkMailMan_put_SendBufferSize(swigCPtr, this, newVal);
  }

  public boolean get_SendIndividual() {
    return chilkatJNI.CkMailMan_get_SendIndividual(swigCPtr, this);
  }

  public void put_SendIndividual(boolean newVal) {
    chilkatJNI.CkMailMan_put_SendIndividual(swigCPtr, this, newVal);
  }

  public int get_SizeLimit() {
    return chilkatJNI.CkMailMan_get_SizeLimit(swigCPtr, this);
  }

  public void put_SizeLimit(int newVal) {
    chilkatJNI.CkMailMan_put_SizeLimit(swigCPtr, this, newVal);
  }

  public void get_SmtpAuthMethod(CkString str) {
    chilkatJNI.CkMailMan_get_SmtpAuthMethod(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String smtpAuthMethod() {
    return chilkatJNI.CkMailMan_smtpAuthMethod(swigCPtr, this);
  }

  public void put_SmtpAuthMethod(String newVal) {
    chilkatJNI.CkMailMan_put_SmtpAuthMethod(swigCPtr, this, newVal);
  }

  public void get_SmtpFailReason(CkString str) {
    chilkatJNI.CkMailMan_get_SmtpFailReason(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String smtpFailReason() {
    return chilkatJNI.CkMailMan_smtpFailReason(swigCPtr, this);
  }

  public void get_SmtpHost(CkString str) {
    chilkatJNI.CkMailMan_get_SmtpHost(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String smtpHost() {
    return chilkatJNI.CkMailMan_smtpHost(swigCPtr, this);
  }

  public void put_SmtpHost(String newVal) {
    chilkatJNI.CkMailMan_put_SmtpHost(swigCPtr, this, newVal);
  }

  public void get_SmtpLoginDomain(CkString str) {
    chilkatJNI.CkMailMan_get_SmtpLoginDomain(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String smtpLoginDomain() {
    return chilkatJNI.CkMailMan_smtpLoginDomain(swigCPtr, this);
  }

  public void put_SmtpLoginDomain(String newVal) {
    chilkatJNI.CkMailMan_put_SmtpLoginDomain(swigCPtr, this, newVal);
  }

  public void get_SmtpPassword(CkString str) {
    chilkatJNI.CkMailMan_get_SmtpPassword(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String smtpPassword() {
    return chilkatJNI.CkMailMan_smtpPassword(swigCPtr, this);
  }

  public void put_SmtpPassword(String newVal) {
    chilkatJNI.CkMailMan_put_SmtpPassword(swigCPtr, this, newVal);
  }

  public boolean get_SmtpPipelining() {
    return chilkatJNI.CkMailMan_get_SmtpPipelining(swigCPtr, this);
  }

  public void put_SmtpPipelining(boolean newVal) {
    chilkatJNI.CkMailMan_put_SmtpPipelining(swigCPtr, this, newVal);
  }

  public int get_SmtpPort() {
    return chilkatJNI.CkMailMan_get_SmtpPort(swigCPtr, this);
  }

  public void put_SmtpPort(int newVal) {
    chilkatJNI.CkMailMan_put_SmtpPort(swigCPtr, this, newVal);
  }

  public void get_SmtpSessionLog(CkString str) {
    chilkatJNI.CkMailMan_get_SmtpSessionLog(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String smtpSessionLog() {
    return chilkatJNI.CkMailMan_smtpSessionLog(swigCPtr, this);
  }

  public boolean get_SmtpSsl() {
    return chilkatJNI.CkMailMan_get_SmtpSsl(swigCPtr, this);
  }

  public void put_SmtpSsl(boolean newVal) {
    chilkatJNI.CkMailMan_put_SmtpSsl(swigCPtr, this, newVal);
  }

  public boolean get_SmtpSslServerCertVerified() {
    return chilkatJNI.CkMailMan_get_SmtpSslServerCertVerified(swigCPtr, this);
  }

  public void get_SmtpUsername(CkString str) {
    chilkatJNI.CkMailMan_get_SmtpUsername(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String smtpUsername() {
    return chilkatJNI.CkMailMan_smtpUsername(swigCPtr, this);
  }

  public void put_SmtpUsername(String newVal) {
    chilkatJNI.CkMailMan_put_SmtpUsername(swigCPtr, this, newVal);
  }

  public int get_SoRcvBuf() {
    return chilkatJNI.CkMailMan_get_SoRcvBuf(swigCPtr, this);
  }

  public void put_SoRcvBuf(int newVal) {
    chilkatJNI.CkMailMan_put_SoRcvBuf(swigCPtr, this, newVal);
  }

  public int get_SoSndBuf() {
    return chilkatJNI.CkMailMan_get_SoSndBuf(swigCPtr, this);
  }

  public void put_SoSndBuf(int newVal) {
    chilkatJNI.CkMailMan_put_SoSndBuf(swigCPtr, this, newVal);
  }

  public void get_SocksHostname(CkString str) {
    chilkatJNI.CkMailMan_get_SocksHostname(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String socksHostname() {
    return chilkatJNI.CkMailMan_socksHostname(swigCPtr, this);
  }

  public void put_SocksHostname(String newVal) {
    chilkatJNI.CkMailMan_put_SocksHostname(swigCPtr, this, newVal);
  }

  public void get_SocksPassword(CkString str) {
    chilkatJNI.CkMailMan_get_SocksPassword(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String socksPassword() {
    return chilkatJNI.CkMailMan_socksPassword(swigCPtr, this);
  }

  public void put_SocksPassword(String newVal) {
    chilkatJNI.CkMailMan_put_SocksPassword(swigCPtr, this, newVal);
  }

  public int get_SocksPort() {
    return chilkatJNI.CkMailMan_get_SocksPort(swigCPtr, this);
  }

  public void put_SocksPort(int newVal) {
    chilkatJNI.CkMailMan_put_SocksPort(swigCPtr, this, newVal);
  }

  public void get_SocksUsername(CkString str) {
    chilkatJNI.CkMailMan_get_SocksUsername(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String socksUsername() {
    return chilkatJNI.CkMailMan_socksUsername(swigCPtr, this);
  }

  public void put_SocksUsername(String newVal) {
    chilkatJNI.CkMailMan_put_SocksUsername(swigCPtr, this, newVal);
  }

  public int get_SocksVersion() {
    return chilkatJNI.CkMailMan_get_SocksVersion(swigCPtr, this);
  }

  public void put_SocksVersion(int newVal) {
    chilkatJNI.CkMailMan_put_SocksVersion(swigCPtr, this, newVal);
  }

  public void get_SslAllowedCiphers(CkString str) {
    chilkatJNI.CkMailMan_get_SslAllowedCiphers(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String sslAllowedCiphers() {
    return chilkatJNI.CkMailMan_sslAllowedCiphers(swigCPtr, this);
  }

  public void put_SslAllowedCiphers(String newVal) {
    chilkatJNI.CkMailMan_put_SslAllowedCiphers(swigCPtr, this, newVal);
  }

  public void get_SslProtocol(CkString str) {
    chilkatJNI.CkMailMan_get_SslProtocol(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String sslProtocol() {
    return chilkatJNI.CkMailMan_sslProtocol(swigCPtr, this);
  }

  public void put_SslProtocol(String newVal) {
    chilkatJNI.CkMailMan_put_SslProtocol(swigCPtr, this, newVal);
  }

  public boolean get_StartTLS() {
    return chilkatJNI.CkMailMan_get_StartTLS(swigCPtr, this);
  }

  public void put_StartTLS(boolean newVal) {
    chilkatJNI.CkMailMan_put_StartTLS(swigCPtr, this, newVal);
  }

  public void get_TlsCipherSuite(CkString str) {
    chilkatJNI.CkMailMan_get_TlsCipherSuite(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String tlsCipherSuite() {
    return chilkatJNI.CkMailMan_tlsCipherSuite(swigCPtr, this);
  }

  public void get_TlsPinSet(CkString str) {
    chilkatJNI.CkMailMan_get_TlsPinSet(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String tlsPinSet() {
    return chilkatJNI.CkMailMan_tlsPinSet(swigCPtr, this);
  }

  public void put_TlsPinSet(String newVal) {
    chilkatJNI.CkMailMan_put_TlsPinSet(swigCPtr, this, newVal);
  }

  public void get_TlsVersion(CkString str) {
    chilkatJNI.CkMailMan_get_TlsVersion(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String tlsVersion() {
    return chilkatJNI.CkMailMan_tlsVersion(swigCPtr, this);
  }

  public boolean get_UseApop() {
    return chilkatJNI.CkMailMan_get_UseApop(swigCPtr, this);
  }

  public void put_UseApop(boolean newVal) {
    chilkatJNI.CkMailMan_put_UseApop(swigCPtr, this, newVal);
  }

  public boolean AddPfxSourceData(CkByteData pfxData, String password) {
    return chilkatJNI.CkMailMan_AddPfxSourceData(swigCPtr, this, CkByteData.getCPtr(pfxData), pfxData, password);
  }

  public boolean AddPfxSourceFile(String pfxFilePath, String password) {
    return chilkatJNI.CkMailMan_AddPfxSourceFile(swigCPtr, this, pfxFilePath, password);
  }

  public int CheckMail() {
    return chilkatJNI.CkMailMan_CheckMail(swigCPtr, this);
  }

  public CkTask CheckMailAsync() {
    long cPtr = chilkatJNI.CkMailMan_CheckMailAsync(swigCPtr, this);
    return (cPtr == 0) ? null : new CkTask(cPtr, true);
  }

  public void ClearBadEmailAddresses() {
    chilkatJNI.CkMailMan_ClearBadEmailAddresses(swigCPtr, this);
  }

  public void ClearPop3SessionLog() {
    chilkatJNI.CkMailMan_ClearPop3SessionLog(swigCPtr, this);
  }

  public void ClearSmtpSessionLog() {
    chilkatJNI.CkMailMan_ClearSmtpSessionLog(swigCPtr, this);
  }

  public boolean CloseSmtpConnection() {
    return chilkatJNI.CkMailMan_CloseSmtpConnection(swigCPtr, this);
  }

  public CkTask CloseSmtpConnectionAsync() {
    long cPtr = chilkatJNI.CkMailMan_CloseSmtpConnectionAsync(swigCPtr, this);
    return (cPtr == 0) ? null : new CkTask(cPtr, true);
  }

  public CkEmailBundle CopyMail() {
    long cPtr = chilkatJNI.CkMailMan_CopyMail(swigCPtr, this);
    return (cPtr == 0) ? null : new CkEmailBundle(cPtr, true);
  }

  public CkTask CopyMailAsync() {
    long cPtr = chilkatJNI.CkMailMan_CopyMailAsync(swigCPtr, this);
    return (cPtr == 0) ? null : new CkTask(cPtr, true);
  }

  public boolean DeleteBundle(CkEmailBundle bundle) {
    return chilkatJNI.CkMailMan_DeleteBundle(swigCPtr, this, CkEmailBundle.getCPtr(bundle), bundle);
  }

  public CkTask DeleteBundleAsync(CkEmailBundle bundle) {
    long cPtr = chilkatJNI.CkMailMan_DeleteBundleAsync(swigCPtr, this, CkEmailBundle.getCPtr(bundle), bundle);
    return (cPtr == 0) ? null : new CkTask(cPtr, true);
  }

  public boolean DeleteByMsgnum(int msgnum) {
    return chilkatJNI.CkMailMan_DeleteByMsgnum(swigCPtr, this, msgnum);
  }

  public CkTask DeleteByMsgnumAsync(int msgnum) {
    long cPtr = chilkatJNI.CkMailMan_DeleteByMsgnumAsync(swigCPtr, this, msgnum);
    return (cPtr == 0) ? null : new CkTask(cPtr, true);
  }

  public boolean DeleteByUidl(String uidl) {
    return chilkatJNI.CkMailMan_DeleteByUidl(swigCPtr, this, uidl);
  }

  public CkTask DeleteByUidlAsync(String uidl) {
    long cPtr = chilkatJNI.CkMailMan_DeleteByUidlAsync(swigCPtr, this, uidl);
    return (cPtr == 0) ? null : new CkTask(cPtr, true);
  }

  public boolean DeleteEmail(CkEmail email) {
    return chilkatJNI.CkMailMan_DeleteEmail(swigCPtr, this, CkEmail.getCPtr(email), email);
  }

  public CkTask DeleteEmailAsync(CkEmail email) {
    long cPtr = chilkatJNI.CkMailMan_DeleteEmailAsync(swigCPtr, this, CkEmail.getCPtr(email), email);
    return (cPtr == 0) ? null : new CkTask(cPtr, true);
  }

  public boolean DeleteMultiple(CkStringArray uidlArray) {
    return chilkatJNI.CkMailMan_DeleteMultiple(swigCPtr, this, CkStringArray.getCPtr(uidlArray), uidlArray);
  }

  public CkTask DeleteMultipleAsync(CkStringArray uidlArray) {
    long cPtr = chilkatJNI.CkMailMan_DeleteMultipleAsync(swigCPtr, this, CkStringArray.getCPtr(uidlArray), uidlArray);
    return (cPtr == 0) ? null : new CkTask(cPtr, true);
  }

  public CkEmail FetchByMsgnum(int msgnum) {
    long cPtr = chilkatJNI.CkMailMan_FetchByMsgnum(swigCPtr, this, msgnum);
    return (cPtr == 0) ? null : new CkEmail(cPtr, true);
  }

  public CkTask FetchByMsgnumAsync(int msgnum) {
    long cPtr = chilkatJNI.CkMailMan_FetchByMsgnumAsync(swigCPtr, this, msgnum);
    return (cPtr == 0) ? null : new CkTask(cPtr, true);
  }

  public CkEmail FetchEmail(String uidl) {
    long cPtr = chilkatJNI.CkMailMan_FetchEmail(swigCPtr, this, uidl);
    return (cPtr == 0) ? null : new CkEmail(cPtr, true);
  }

  public CkTask FetchEmailAsync(String uidl) {
    long cPtr = chilkatJNI.CkMailMan_FetchEmailAsync(swigCPtr, this, uidl);
    return (cPtr == 0) ? null : new CkTask(cPtr, true);
  }

  public boolean FetchMime(String uidl, CkByteData outData) {
    return chilkatJNI.CkMailMan_FetchMime(swigCPtr, this, uidl, CkByteData.getCPtr(outData), outData);
  }

  public CkTask FetchMimeAsync(String uidl) {
    long cPtr = chilkatJNI.CkMailMan_FetchMimeAsync(swigCPtr, this, uidl);
    return (cPtr == 0) ? null : new CkTask(cPtr, true);
  }

  public boolean FetchMimeByMsgnum(int msgnum, CkByteData outBytes) {
    return chilkatJNI.CkMailMan_FetchMimeByMsgnum(swigCPtr, this, msgnum, CkByteData.getCPtr(outBytes), outBytes);
  }

  public CkTask FetchMimeByMsgnumAsync(int msgnum) {
    long cPtr = chilkatJNI.CkMailMan_FetchMimeByMsgnumAsync(swigCPtr, this, msgnum);
    return (cPtr == 0) ? null : new CkTask(cPtr, true);
  }

  public CkEmailBundle FetchMultiple(CkStringArray uidlArray) {
    long cPtr = chilkatJNI.CkMailMan_FetchMultiple(swigCPtr, this, CkStringArray.getCPtr(uidlArray), uidlArray);
    return (cPtr == 0) ? null : new CkEmailBundle(cPtr, true);
  }

  public CkTask FetchMultipleAsync(CkStringArray uidlArray) {
    long cPtr = chilkatJNI.CkMailMan_FetchMultipleAsync(swigCPtr, this, CkStringArray.getCPtr(uidlArray), uidlArray);
    return (cPtr == 0) ? null : new CkTask(cPtr, true);
  }

  public CkEmailBundle FetchMultipleHeaders(CkStringArray uidlArray, int numBodyLines) {
    long cPtr = chilkatJNI.CkMailMan_FetchMultipleHeaders(swigCPtr, this, CkStringArray.getCPtr(uidlArray), uidlArray, numBodyLines);
    return (cPtr == 0) ? null : new CkEmailBundle(cPtr, true);
  }

  public CkTask FetchMultipleHeadersAsync(CkStringArray uidlArray, int numBodyLines) {
    long cPtr = chilkatJNI.CkMailMan_FetchMultipleHeadersAsync(swigCPtr, this, CkStringArray.getCPtr(uidlArray), uidlArray, numBodyLines);
    return (cPtr == 0) ? null : new CkTask(cPtr, true);
  }

  public CkStringArray FetchMultipleMime(CkStringArray uidlArray) {
    long cPtr = chilkatJNI.CkMailMan_FetchMultipleMime(swigCPtr, this, CkStringArray.getCPtr(uidlArray), uidlArray);
    return (cPtr == 0) ? null : new CkStringArray(cPtr, true);
  }

  public CkTask FetchMultipleMimeAsync(CkStringArray uidlArray) {
    long cPtr = chilkatJNI.CkMailMan_FetchMultipleMimeAsync(swigCPtr, this, CkStringArray.getCPtr(uidlArray), uidlArray);
    return (cPtr == 0) ? null : new CkTask(cPtr, true);
  }

  public CkEmail FetchSingleHeader(int numBodyLines, int index) {
    long cPtr = chilkatJNI.CkMailMan_FetchSingleHeader(swigCPtr, this, numBodyLines, index);
    return (cPtr == 0) ? null : new CkEmail(cPtr, true);
  }

  public CkTask FetchSingleHeaderAsync(int numBodyLines, int index) {
    long cPtr = chilkatJNI.CkMailMan_FetchSingleHeaderAsync(swigCPtr, this, numBodyLines, index);
    return (cPtr == 0) ? null : new CkTask(cPtr, true);
  }

  public CkEmail FetchSingleHeaderByUidl(int numBodyLines, String uidl) {
    long cPtr = chilkatJNI.CkMailMan_FetchSingleHeaderByUidl(swigCPtr, this, numBodyLines, uidl);
    return (cPtr == 0) ? null : new CkEmail(cPtr, true);
  }

  public CkTask FetchSingleHeaderByUidlAsync(int numBodyLines, String uidl) {
    long cPtr = chilkatJNI.CkMailMan_FetchSingleHeaderByUidlAsync(swigCPtr, this, numBodyLines, uidl);
    return (cPtr == 0) ? null : new CkTask(cPtr, true);
  }

  public CkEmailBundle GetAllHeaders(int numBodyLines) {
    long cPtr = chilkatJNI.CkMailMan_GetAllHeaders(swigCPtr, this, numBodyLines);
    return (cPtr == 0) ? null : new CkEmailBundle(cPtr, true);
  }

  public CkTask GetAllHeadersAsync(int numBodyLines) {
    long cPtr = chilkatJNI.CkMailMan_GetAllHeadersAsync(swigCPtr, this, numBodyLines);
    return (cPtr == 0) ? null : new CkTask(cPtr, true);
  }

  public CkStringArray GetBadEmailAddrs() {
    long cPtr = chilkatJNI.CkMailMan_GetBadEmailAddrs(swigCPtr, this);
    return (cPtr == 0) ? null : new CkStringArray(cPtr, true);
  }

  public CkEmail GetFullEmail(CkEmail email) {
    long cPtr = chilkatJNI.CkMailMan_GetFullEmail(swigCPtr, this, CkEmail.getCPtr(email), email);
    return (cPtr == 0) ? null : new CkEmail(cPtr, true);
  }

  public CkTask GetFullEmailAsync(CkEmail email) {
    long cPtr = chilkatJNI.CkMailMan_GetFullEmailAsync(swigCPtr, this, CkEmail.getCPtr(email), email);
    return (cPtr == 0) ? null : new CkTask(cPtr, true);
  }

  public CkEmailBundle GetHeaders(int numBodyLines, int fromIndex, int toIndex) {
    long cPtr = chilkatJNI.CkMailMan_GetHeaders(swigCPtr, this, numBodyLines, fromIndex, toIndex);
    return (cPtr == 0) ? null : new CkEmailBundle(cPtr, true);
  }

  public CkTask GetHeadersAsync(int numBodyLines, int fromIndex, int toIndex) {
    long cPtr = chilkatJNI.CkMailMan_GetHeadersAsync(swigCPtr, this, numBodyLines, fromIndex, toIndex);
    return (cPtr == 0) ? null : new CkTask(cPtr, true);
  }

  public int GetMailboxCount() {
    return chilkatJNI.CkMailMan_GetMailboxCount(swigCPtr, this);
  }

  public CkTask GetMailboxCountAsync() {
    long cPtr = chilkatJNI.CkMailMan_GetMailboxCountAsync(swigCPtr, this);
    return (cPtr == 0) ? null : new CkTask(cPtr, true);
  }

  public boolean GetMailboxInfoXml(CkString outXml) {
    return chilkatJNI.CkMailMan_GetMailboxInfoXml(swigCPtr, this, CkString.getCPtr(outXml), outXml);
  }

  public String getMailboxInfoXml() {
    return chilkatJNI.CkMailMan_getMailboxInfoXml(swigCPtr, this);
  }

  public String mailboxInfoXml() {
    return chilkatJNI.CkMailMan_mailboxInfoXml(swigCPtr, this);
  }

  public CkTask GetMailboxInfoXmlAsync() {
    long cPtr = chilkatJNI.CkMailMan_GetMailboxInfoXmlAsync(swigCPtr, this);
    return (cPtr == 0) ? null : new CkTask(cPtr, true);
  }

  public long GetMailboxSize() {
    return chilkatJNI.CkMailMan_GetMailboxSize(swigCPtr, this);
  }

  public CkTask GetMailboxSizeAsync() {
    long cPtr = chilkatJNI.CkMailMan_GetMailboxSizeAsync(swigCPtr, this);
    return (cPtr == 0) ? null : new CkTask(cPtr, true);
  }

  public CkCert GetPop3SslServerCert() {
    long cPtr = chilkatJNI.CkMailMan_GetPop3SslServerCert(swigCPtr, this);
    return (cPtr == 0) ? null : new CkCert(cPtr, true);
  }

  public CkStringArray GetSentToEmailAddrs() {
    long cPtr = chilkatJNI.CkMailMan_GetSentToEmailAddrs(swigCPtr, this);
    return (cPtr == 0) ? null : new CkStringArray(cPtr, true);
  }

  public int GetSizeByUidl(String uidl) {
    return chilkatJNI.CkMailMan_GetSizeByUidl(swigCPtr, this, uidl);
  }

  public CkTask GetSizeByUidlAsync(String uidl) {
    long cPtr = chilkatJNI.CkMailMan_GetSizeByUidlAsync(swigCPtr, this, uidl);
    return (cPtr == 0) ? null : new CkTask(cPtr, true);
  }

  public CkCert GetSmtpSslServerCert() {
    long cPtr = chilkatJNI.CkMailMan_GetSmtpSslServerCert(swigCPtr, this);
    return (cPtr == 0) ? null : new CkCert(cPtr, true);
  }

  public CkStringArray GetUidls() {
    long cPtr = chilkatJNI.CkMailMan_GetUidls(swigCPtr, this);
    return (cPtr == 0) ? null : new CkStringArray(cPtr, true);
  }

  public CkTask GetUidlsAsync() {
    long cPtr = chilkatJNI.CkMailMan_GetUidlsAsync(swigCPtr, this);
    return (cPtr == 0) ? null : new CkTask(cPtr, true);
  }

  public boolean IsSmtpDsnCapable() {
    return chilkatJNI.CkMailMan_IsSmtpDsnCapable(swigCPtr, this);
  }

  public CkTask IsSmtpDsnCapableAsync() {
    long cPtr = chilkatJNI.CkMailMan_IsSmtpDsnCapableAsync(swigCPtr, this);
    return (cPtr == 0) ? null : new CkTask(cPtr, true);
  }

  public boolean IsUnlocked() {
    return chilkatJNI.CkMailMan_IsUnlocked(swigCPtr, this);
  }

  public CkEmail LoadEml(String emlFilename) {
    long cPtr = chilkatJNI.CkMailMan_LoadEml(swigCPtr, this, emlFilename);
    return (cPtr == 0) ? null : new CkEmail(cPtr, true);
  }

  public CkEmailBundle LoadMbx(String mbxFileName) {
    long cPtr = chilkatJNI.CkMailMan_LoadMbx(swigCPtr, this, mbxFileName);
    return (cPtr == 0) ? null : new CkEmailBundle(cPtr, true);
  }

  public CkEmail LoadMime(String mimeText) {
    long cPtr = chilkatJNI.CkMailMan_LoadMime(swigCPtr, this, mimeText);
    return (cPtr == 0) ? null : new CkEmail(cPtr, true);
  }

  public CkEmail LoadXmlEmail(String filename) {
    long cPtr = chilkatJNI.CkMailMan_LoadXmlEmail(swigCPtr, this, filename);
    return (cPtr == 0) ? null : new CkEmail(cPtr, true);
  }

  public CkEmail LoadXmlEmailString(String xmlString) {
    long cPtr = chilkatJNI.CkMailMan_LoadXmlEmailString(swigCPtr, this, xmlString);
    return (cPtr == 0) ? null : new CkEmail(cPtr, true);
  }

  public CkEmailBundle LoadXmlFile(String filename) {
    long cPtr = chilkatJNI.CkMailMan_LoadXmlFile(swigCPtr, this, filename);
    return (cPtr == 0) ? null : new CkEmailBundle(cPtr, true);
  }

  public CkEmailBundle LoadXmlString(String xmlString) {
    long cPtr = chilkatJNI.CkMailMan_LoadXmlString(swigCPtr, this, xmlString);
    return (cPtr == 0) ? null : new CkEmailBundle(cPtr, true);
  }

  public boolean MxLookup(String emailAddress, CkString outStrHostname) {
    return chilkatJNI.CkMailMan_MxLookup(swigCPtr, this, emailAddress, CkString.getCPtr(outStrHostname), outStrHostname);
  }

  public String mxLookup(String emailAddress) {
    return chilkatJNI.CkMailMan_mxLookup(swigCPtr, this, emailAddress);
  }

  public CkStringArray MxLookupAll(String emailAddress) {
    long cPtr = chilkatJNI.CkMailMan_MxLookupAll(swigCPtr, this, emailAddress);
    return (cPtr == 0) ? null : new CkStringArray(cPtr, true);
  }

  public boolean OpenSmtpConnection() {
    return chilkatJNI.CkMailMan_OpenSmtpConnection(swigCPtr, this);
  }

  public CkTask OpenSmtpConnectionAsync() {
    long cPtr = chilkatJNI.CkMailMan_OpenSmtpConnectionAsync(swigCPtr, this);
    return (cPtr == 0) ? null : new CkTask(cPtr, true);
  }

  public boolean Pop3Authenticate() {
    return chilkatJNI.CkMailMan_Pop3Authenticate(swigCPtr, this);
  }

  public CkTask Pop3AuthenticateAsync() {
    long cPtr = chilkatJNI.CkMailMan_Pop3AuthenticateAsync(swigCPtr, this);
    return (cPtr == 0) ? null : new CkTask(cPtr, true);
  }

  public boolean Pop3BeginSession() {
    return chilkatJNI.CkMailMan_Pop3BeginSession(swigCPtr, this);
  }

  public CkTask Pop3BeginSessionAsync() {
    long cPtr = chilkatJNI.CkMailMan_Pop3BeginSessionAsync(swigCPtr, this);
    return (cPtr == 0) ? null : new CkTask(cPtr, true);
  }

  public boolean Pop3Connect() {
    return chilkatJNI.CkMailMan_Pop3Connect(swigCPtr, this);
  }

  public CkTask Pop3ConnectAsync() {
    long cPtr = chilkatJNI.CkMailMan_Pop3ConnectAsync(swigCPtr, this);
    return (cPtr == 0) ? null : new CkTask(cPtr, true);
  }

  public boolean Pop3EndSession() {
    return chilkatJNI.CkMailMan_Pop3EndSession(swigCPtr, this);
  }

  public CkTask Pop3EndSessionAsync() {
    long cPtr = chilkatJNI.CkMailMan_Pop3EndSessionAsync(swigCPtr, this);
    return (cPtr == 0) ? null : new CkTask(cPtr, true);
  }

  public boolean Pop3EndSessionNoQuit() {
    return chilkatJNI.CkMailMan_Pop3EndSessionNoQuit(swigCPtr, this);
  }

  public CkTask Pop3EndSessionNoQuitAsync() {
    long cPtr = chilkatJNI.CkMailMan_Pop3EndSessionNoQuitAsync(swigCPtr, this);
    return (cPtr == 0) ? null : new CkTask(cPtr, true);
  }

  public boolean Pop3Noop() {
    return chilkatJNI.CkMailMan_Pop3Noop(swigCPtr, this);
  }

  public CkTask Pop3NoopAsync() {
    long cPtr = chilkatJNI.CkMailMan_Pop3NoopAsync(swigCPtr, this);
    return (cPtr == 0) ? null : new CkTask(cPtr, true);
  }

  public boolean Pop3Reset() {
    return chilkatJNI.CkMailMan_Pop3Reset(swigCPtr, this);
  }

  public CkTask Pop3ResetAsync() {
    long cPtr = chilkatJNI.CkMailMan_Pop3ResetAsync(swigCPtr, this);
    return (cPtr == 0) ? null : new CkTask(cPtr, true);
  }

  public boolean Pop3SendRawCommand(String command, String charset, CkString outStr) {
    return chilkatJNI.CkMailMan_Pop3SendRawCommand(swigCPtr, this, command, charset, CkString.getCPtr(outStr), outStr);
  }

  public String pop3SendRawCommand(String command, String charset) {
    return chilkatJNI.CkMailMan_pop3SendRawCommand(swigCPtr, this, command, charset);
  }

  public CkTask Pop3SendRawCommandAsync(String command, String charset) {
    long cPtr = chilkatJNI.CkMailMan_Pop3SendRawCommandAsync(swigCPtr, this, command, charset);
    return (cPtr == 0) ? null : new CkTask(cPtr, true);
  }

  public boolean QuickSend(String fromAddr, String toAddr, String subject, String body, String smtpServer) {
    return chilkatJNI.CkMailMan_QuickSend(swigCPtr, this, fromAddr, toAddr, subject, body, smtpServer);
  }

  public CkTask QuickSendAsync(String fromAddr, String toAddr, String subject, String body, String smtpServer) {
    long cPtr = chilkatJNI.CkMailMan_QuickSendAsync(swigCPtr, this, fromAddr, toAddr, subject, body, smtpServer);
    return (cPtr == 0) ? null : new CkTask(cPtr, true);
  }

  public boolean RenderToMime(CkEmail email, CkString outStr) {
    return chilkatJNI.CkMailMan_RenderToMime(swigCPtr, this, CkEmail.getCPtr(email), email, CkString.getCPtr(outStr), outStr);
  }

  public String renderToMime(CkEmail email) {
    return chilkatJNI.CkMailMan_renderToMime(swigCPtr, this, CkEmail.getCPtr(email), email);
  }

  public boolean RenderToMimeBytes(CkEmail email, CkByteData outBytes) {
    return chilkatJNI.CkMailMan_RenderToMimeBytes(swigCPtr, this, CkEmail.getCPtr(email), email, CkByteData.getCPtr(outBytes), outBytes);
  }

  public boolean SendBundle(CkEmailBundle bundle) {
    return chilkatJNI.CkMailMan_SendBundle(swigCPtr, this, CkEmailBundle.getCPtr(bundle), bundle);
  }

  public CkTask SendBundleAsync(CkEmailBundle bundle) {
    long cPtr = chilkatJNI.CkMailMan_SendBundleAsync(swigCPtr, this, CkEmailBundle.getCPtr(bundle), bundle);
    return (cPtr == 0) ? null : new CkTask(cPtr, true);
  }

  public boolean SendEmail(CkEmail email) {
    return chilkatJNI.CkMailMan_SendEmail(swigCPtr, this, CkEmail.getCPtr(email), email);
  }

  public CkTask SendEmailAsync(CkEmail email) {
    long cPtr = chilkatJNI.CkMailMan_SendEmailAsync(swigCPtr, this, CkEmail.getCPtr(email), email);
    return (cPtr == 0) ? null : new CkTask(cPtr, true);
  }

  public boolean SendMime(String from, String recipients, String mimeText) {
    return chilkatJNI.CkMailMan_SendMime(swigCPtr, this, from, recipients, mimeText);
  }

  public CkTask SendMimeAsync(String from, String recipients, String mimeText) {
    long cPtr = chilkatJNI.CkMailMan_SendMimeAsync(swigCPtr, this, from, recipients, mimeText);
    return (cPtr == 0) ? null : new CkTask(cPtr, true);
  }

  public boolean SendMimeBytes(String from, String recipients, CkByteData mimeData) {
    return chilkatJNI.CkMailMan_SendMimeBytes(swigCPtr, this, from, recipients, CkByteData.getCPtr(mimeData), mimeData);
  }

  public CkTask SendMimeBytesAsync(String from, String recipients, CkByteData mimeData) {
    long cPtr = chilkatJNI.CkMailMan_SendMimeBytesAsync(swigCPtr, this, from, recipients, CkByteData.getCPtr(mimeData), mimeData);
    return (cPtr == 0) ? null : new CkTask(cPtr, true);
  }

  public boolean SendMimeToList(String from, String distListFile, String mimeText) {
    return chilkatJNI.CkMailMan_SendMimeToList(swigCPtr, this, from, distListFile, mimeText);
  }

  public CkTask SendMimeToListAsync(String from, String distListFile, String mimeText) {
    long cPtr = chilkatJNI.CkMailMan_SendMimeToListAsync(swigCPtr, this, from, distListFile, mimeText);
    return (cPtr == 0) ? null : new CkTask(cPtr, true);
  }

  public boolean SendToDistributionList(CkEmail email, CkStringArray sa) {
    return chilkatJNI.CkMailMan_SendToDistributionList(swigCPtr, this, CkEmail.getCPtr(email), email, CkStringArray.getCPtr(sa), sa);
  }

  public CkTask SendToDistributionListAsync(CkEmail email, CkStringArray sa) {
    long cPtr = chilkatJNI.CkMailMan_SendToDistributionListAsync(swigCPtr, this, CkEmail.getCPtr(email), email, CkStringArray.getCPtr(sa), sa);
    return (cPtr == 0) ? null : new CkTask(cPtr, true);
  }

  public boolean SetDecryptCert(CkCert cert) {
    return chilkatJNI.CkMailMan_SetDecryptCert(swigCPtr, this, CkCert.getCPtr(cert), cert);
  }

  public boolean SetDecryptCert2(CkCert cert, CkPrivateKey key) {
    return chilkatJNI.CkMailMan_SetDecryptCert2(swigCPtr, this, CkCert.getCPtr(cert), cert, CkPrivateKey.getCPtr(key), key);
  }

  public boolean SetSslClientCert(CkCert cert) {
    return chilkatJNI.CkMailMan_SetSslClientCert(swigCPtr, this, CkCert.getCPtr(cert), cert);
  }

  public boolean SetSslClientCertPem(String pemDataOrFilename, String pemPassword) {
    return chilkatJNI.CkMailMan_SetSslClientCertPem(swigCPtr, this, pemDataOrFilename, pemPassword);
  }

  public boolean SetSslClientCertPfx(String pfxFilename, String pfxPassword) {
    return chilkatJNI.CkMailMan_SetSslClientCertPfx(swigCPtr, this, pfxFilename, pfxPassword);
  }

  public boolean SmtpAuthenticate() {
    return chilkatJNI.CkMailMan_SmtpAuthenticate(swigCPtr, this);
  }

  public CkTask SmtpAuthenticateAsync() {
    long cPtr = chilkatJNI.CkMailMan_SmtpAuthenticateAsync(swigCPtr, this);
    return (cPtr == 0) ? null : new CkTask(cPtr, true);
  }

  public boolean SmtpConnect() {
    return chilkatJNI.CkMailMan_SmtpConnect(swigCPtr, this);
  }

  public CkTask SmtpConnectAsync() {
    long cPtr = chilkatJNI.CkMailMan_SmtpConnectAsync(swigCPtr, this);
    return (cPtr == 0) ? null : new CkTask(cPtr, true);
  }

  public boolean SmtpNoop() {
    return chilkatJNI.CkMailMan_SmtpNoop(swigCPtr, this);
  }

  public CkTask SmtpNoopAsync() {
    long cPtr = chilkatJNI.CkMailMan_SmtpNoopAsync(swigCPtr, this);
    return (cPtr == 0) ? null : new CkTask(cPtr, true);
  }

  public boolean SmtpReset() {
    return chilkatJNI.CkMailMan_SmtpReset(swigCPtr, this);
  }

  public CkTask SmtpResetAsync() {
    long cPtr = chilkatJNI.CkMailMan_SmtpResetAsync(swigCPtr, this);
    return (cPtr == 0) ? null : new CkTask(cPtr, true);
  }

  public boolean SmtpSendRawCommand(String command, String charset, boolean bEncodeBase64, CkString outStr) {
    return chilkatJNI.CkMailMan_SmtpSendRawCommand(swigCPtr, this, command, charset, bEncodeBase64, CkString.getCPtr(outStr), outStr);
  }

  public String smtpSendRawCommand(String command, String charset, boolean bEncodeBase64) {
    return chilkatJNI.CkMailMan_smtpSendRawCommand(swigCPtr, this, command, charset, bEncodeBase64);
  }

  public CkTask SmtpSendRawCommandAsync(String command, String charset, boolean bEncodeBase64) {
    long cPtr = chilkatJNI.CkMailMan_SmtpSendRawCommandAsync(swigCPtr, this, command, charset, bEncodeBase64);
    return (cPtr == 0) ? null : new CkTask(cPtr, true);
  }

  public boolean SshAuthenticatePk(String sshLogin, CkSshKey privateKey) {
    return chilkatJNI.CkMailMan_SshAuthenticatePk(swigCPtr, this, sshLogin, CkSshKey.getCPtr(privateKey), privateKey);
  }

  public CkTask SshAuthenticatePkAsync(String sshLogin, CkSshKey privateKey) {
    long cPtr = chilkatJNI.CkMailMan_SshAuthenticatePkAsync(swigCPtr, this, sshLogin, CkSshKey.getCPtr(privateKey), privateKey);
    return (cPtr == 0) ? null : new CkTask(cPtr, true);
  }

  public boolean SshAuthenticatePw(String sshLogin, String sshPassword) {
    return chilkatJNI.CkMailMan_SshAuthenticatePw(swigCPtr, this, sshLogin, sshPassword);
  }

  public CkTask SshAuthenticatePwAsync(String sshLogin, String sshPassword) {
    long cPtr = chilkatJNI.CkMailMan_SshAuthenticatePwAsync(swigCPtr, this, sshLogin, sshPassword);
    return (cPtr == 0) ? null : new CkTask(cPtr, true);
  }

  public boolean SshCloseTunnel() {
    return chilkatJNI.CkMailMan_SshCloseTunnel(swigCPtr, this);
  }

  public CkTask SshCloseTunnelAsync() {
    long cPtr = chilkatJNI.CkMailMan_SshCloseTunnelAsync(swigCPtr, this);
    return (cPtr == 0) ? null : new CkTask(cPtr, true);
  }

  public boolean SshOpenTunnel(String sshHostname, int sshPort) {
    return chilkatJNI.CkMailMan_SshOpenTunnel(swigCPtr, this, sshHostname, sshPort);
  }

  public CkTask SshOpenTunnelAsync(String sshHostname, int sshPort) {
    long cPtr = chilkatJNI.CkMailMan_SshOpenTunnelAsync(swigCPtr, this, sshHostname, sshPort);
    return (cPtr == 0) ? null : new CkTask(cPtr, true);
  }

  public CkEmailBundle TransferMail() {
    long cPtr = chilkatJNI.CkMailMan_TransferMail(swigCPtr, this);
    return (cPtr == 0) ? null : new CkEmailBundle(cPtr, true);
  }

  public CkTask TransferMailAsync() {
    long cPtr = chilkatJNI.CkMailMan_TransferMailAsync(swigCPtr, this);
    return (cPtr == 0) ? null : new CkTask(cPtr, true);
  }

  public CkStringArray TransferMultipleMime(CkStringArray uidlArray) {
    long cPtr = chilkatJNI.CkMailMan_TransferMultipleMime(swigCPtr, this, CkStringArray.getCPtr(uidlArray), uidlArray);
    return (cPtr == 0) ? null : new CkStringArray(cPtr, true);
  }

  public CkTask TransferMultipleMimeAsync(CkStringArray uidlArray) {
    long cPtr = chilkatJNI.CkMailMan_TransferMultipleMimeAsync(swigCPtr, this, CkStringArray.getCPtr(uidlArray), uidlArray);
    return (cPtr == 0) ? null : new CkTask(cPtr, true);
  }

  public boolean UnlockComponent(String code) {
    return chilkatJNI.CkMailMan_UnlockComponent(swigCPtr, this, code);
  }

  public boolean UseCertVault(CkXmlCertVault vault) {
    return chilkatJNI.CkMailMan_UseCertVault(swigCPtr, this, CkXmlCertVault.getCPtr(vault), vault);
  }

  public boolean UseSsh(CkSsh ssh) {
    return chilkatJNI.CkMailMan_UseSsh(swigCPtr, this, CkSsh.getCPtr(ssh), ssh);
  }

  public boolean UseSshTunnel(CkSocket tunnel) {
    return chilkatJNI.CkMailMan_UseSshTunnel(swigCPtr, this, CkSocket.getCPtr(tunnel), tunnel);
  }

  public boolean VerifyPopConnection() {
    return chilkatJNI.CkMailMan_VerifyPopConnection(swigCPtr, this);
  }

  public CkTask VerifyPopConnectionAsync() {
    long cPtr = chilkatJNI.CkMailMan_VerifyPopConnectionAsync(swigCPtr, this);
    return (cPtr == 0) ? null : new CkTask(cPtr, true);
  }

  public boolean VerifyPopLogin() {
    return chilkatJNI.CkMailMan_VerifyPopLogin(swigCPtr, this);
  }

  public CkTask VerifyPopLoginAsync() {
    long cPtr = chilkatJNI.CkMailMan_VerifyPopLoginAsync(swigCPtr, this);
    return (cPtr == 0) ? null : new CkTask(cPtr, true);
  }

  public boolean VerifyRecips(CkEmail email, CkStringArray badAddrs) {
    return chilkatJNI.CkMailMan_VerifyRecips(swigCPtr, this, CkEmail.getCPtr(email), email, CkStringArray.getCPtr(badAddrs), badAddrs);
  }

  public CkTask VerifyRecipsAsync(CkEmail email, CkStringArray badAddrs) {
    long cPtr = chilkatJNI.CkMailMan_VerifyRecipsAsync(swigCPtr, this, CkEmail.getCPtr(email), email, CkStringArray.getCPtr(badAddrs), badAddrs);
    return (cPtr == 0) ? null : new CkTask(cPtr, true);
  }

  public boolean VerifySmtpConnection() {
    return chilkatJNI.CkMailMan_VerifySmtpConnection(swigCPtr, this);
  }

  public CkTask VerifySmtpConnectionAsync() {
    long cPtr = chilkatJNI.CkMailMan_VerifySmtpConnectionAsync(swigCPtr, this);
    return (cPtr == 0) ? null : new CkTask(cPtr, true);
  }

  public boolean VerifySmtpLogin() {
    return chilkatJNI.CkMailMan_VerifySmtpLogin(swigCPtr, this);
  }

  public CkTask VerifySmtpLoginAsync() {
    long cPtr = chilkatJNI.CkMailMan_VerifySmtpLoginAsync(swigCPtr, this);
    return (cPtr == 0) ? null : new CkTask(cPtr, true);
  }

}
